name: Jira check

on: pull_request

jobs:
  pr_checker:
    steps:
      - name: PR jira check
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        uses: vijaykramesh/pr-lint-action@v1.0
