name: Jira check

on: pull_request

jobs:
  pr_checker:
    runs-on: ubuntu-18.04
    steps:
      - name: PR title check
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: 'bash .github/jira.sh'