name: Lint

on: [pull_request, push]

jobs:
  eslint:
    name: Run lint one file
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run npm install
        run: npm install
      - name: Run lint
        run: npm run lint src/index.js